before_script:
 - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
 - echo "Clean up activity can be done here !."
 
cache:
 paths:
 - .m2/repository
 
stages:
 - build
 - deploy

build:
 stage: build
 
deploy_dev:
 stage: deploy
 script:
 - dpl --provider=heroku --app=commande1 --api-key=042936cb-540a-453a-9d86-bf576337504d
 environment:
 name: dev
 url: https://commande1.herokuapp.com/
 only:
 - master

 
deploy_staging:
 stage: deploy
 script:
 - dpl --provider=heroku --app=commande1 --api-key=042936cb-540a-453a-9d86-bf576337504d
 environment:
 name: staging
 url: https://commande1.herokuapp.com/
 only:
 - master
